meta:
  version: &version   'v0.0.1'
  language: &language 'jp_800_5'
  root: &root         "checkpoint"
  root_data: &root_data
    - *root
    - *language
  output_file: &output_file
    - *root_data
    - "output.txt"

model:
  id:
    - 'asr_'
    - *language
    - '_'
    - *version
  rnn_hidden_size:    800
  rnn_hidden_layers:  5
  rnn_type:           nn.GRU
  context:            20
  bidirectional:      true
  label_path:
    - *root_data
    - "labels.json"
  model_path: &model_path
    - *root_data
    - "model.pth"
  decoder:
    top_paths:    1
    beam_width:   10
    lm_path:      null
    alpha:        0.8
    beta:         1
    cutoff_top_n: 40
    cutoff_prob:  1.0
    lm_workers:   1
  audio_conf:
    sample_rate:          16000
    window_size:          .02
    window_stride:        .01
    window:               'hamming'
    speed_volume_perturb: false
    spec_augment:         false
    noise_dir:            null
    noise_prob:           0.4
    noise_min:            0.0
    noise_max:            0.5

dist:  &dist
  dist_url:       'tcp://127.0.0.1:1550'
  dist_backend:   'nccl'
  world_size:     1
  rank:           0
  gpu_rank:       None


trainer:
  log_dir:                  'visualize/deepspeech_final'
  batch_size: &batch_size   50
  cuda:                     True
  num_workers: &num_wokers  32
  epochs:                   1000
  start_epoch:              0
  silent:                   false
  checkpoint_per_batch:     0
  visdom:                   false
  tensorboard:              false
  log_params:               false
  finetune:                 false
  shuffle:                  true
  seed:                     123456
  continue_from: *model_path
  train_manifest:
    - *root_data
    - "train.json"
  val_manifest: &test_manifest
    - *root_data
    - "test.json"
  output_file:               *output_file
  save_folder:               *root_data
  metrics:
    loss: []
    wer: []
    cer: []
  optim:
    max_norm:             400
    learning_anneal:      1.005
    keep_batchnorm_fp32:  null
    loss_scale:           1
    opt_level:            'O1'
    lr:                   0.0003
    momentum:             0.9
    sorta_grad:           true
    nesterov:             true
    weight_decay:         0.00001
  dist:                   null

inference:
  cuda:         true
  half:         false
  dist:         null
  manifest:     *test_manifest
  output_file:  *output_file
  batch_size:   *batch_size
  num_workers:  *num_wokers

windows:
  'hamming':    "scipy.signal.hamming"
  'hann':       "scipy.signal.hann"
  'blackman':   "scipy.signal.blackman"
  'bartlett':   "scipy.signal.bartlett"

supported_rnns:
  'lstm':       "nn.LSTM"
  'rnn':        "nn.RNN"
  'gru':        "nn.GRU"
