meta:
  version:  'v0.0.1'
  language:  'jp_800_5'
  root:       "checkpoint"
  root_data:  "checkpoint/jp_800_5"
  output_file: "checkpoint/jp_800_5/output.txt"

model:
  id: "asr_jp_800_5_v0.0.1"
  rnn_hidden_size:    800
  rnn_hidden_layers:  5
  rnn_type:           nn.GRU
  context:            20
  bidirectional:      true
  label_path: "checkpoint/jp_800_5/labels.json"
  model_path: "checkpoint/jp_800_5/model.pth"
  decoder:
    top_paths:    1
    beam_width:   10
    lm_path:      null
    alpha:        0.8
    beta:         1
    cutoff_top_n: 40
    cutoff_prob:  1.0
    lm_workers:   1
  audio_conf:
    sample_rate:          16000
    window_size:          .02
    window_stride:        .01
    window:               'hamming'
    speed_volume_perturb: false
    spec_augment:         false
    noise_dir:            null
    noise_prob:           0.4
    noise_min:            0.0
    noise_max:            0.5


loaders:
  train_manifest: "checkpoint/jp_800_5/train.json"
  val_manifest: "checkpoint/jp_800_5/test.json"
  batch_size:   40
  num_workers:  32

optim:
  max_norm:             400
  learning_anneal:      1.005
  keep_batchnorm_fp32:  null
  loss_scale:           1
  opt_level:            'O1'
  lr:                   0.0003
  momentum:             0.9
  sorta_grad:           true
  nesterov:             true
  weight_decay:         0.00001
  gamma: 0.7
  step: 1

trainer:
  epochs:                   1000
  model_path: "pth/mnist_cnn.pt"
  checkpoint_path: "pth/mnist_cnn.ckpt.pt"
  device: "cuda"
  device_test: "cpu"

inference:
  cuda:         true
  half:         false
  manifest:     "checkpoint/jp_800_5/test.json"
  output_file:  "checkpoint/jp_800_5/output.txt"
  batch_size:   10
  num_workers:  32
  restart_from: "zakuro://asrdeepspeech/jp_800_5"

windows:
  'hamming':    "scipy.signal.hamming"
  'hann':       "scipy.signal.hann"
  'blackman':   "scipy.signal.blackman"
  'bartlett':   "scipy.signal.bartlett"

supported_rnns:
  'lstm':       "nn.LSTM"
  'rnn':        "nn.RNN"
  'gru':        "nn.GRU"
