meta:
  version:        'v0.0.1'
  language:       'jp_1024_5_LSTM'
  root:           "checkpoint"
  root_data:      "checkpoint/jp_1024_5_LSTM"
  output_file:    "checkpoint/jp_1024_5_LSTM/output.txt"

trainer:
  epochs:                   1000
  model_path:               "checkpoint/jp_1024_5_LSTM/model.pth"
  checkpoint_path:          "checkpoint/jp_1024_5_LSTM/model.ckpt.pth"
  output_file:              "checkpoint/jp_1024_5_LSTM/output.txt"
  device:                   "cuda"
  device_test:              "cuda"
  mixed_precision:          true

loaders:
  train_manifest:           "checkpoint/jp_1024_5_LSTM/train.json"
  val_manifest:             "checkpoint/jp_1024_5_LSTM/test.json"
  batch_size:               64
  num_workers:              32
  caching:                  false
  
model:
  id:                       "asr_jp_1024_5_LSTM_v0.0.1"
  rnn_hidden_size:          1024
  rnn_hidden_layers:        5
  rnn_type:                 nn.LSTM
  context:                  20
  bidirectional:            true
  label_path:               "checkpoint/jp_1024_5_LSTM/labels.json"
  model_path:               "checkpoint/jp_1024_5_LSTM/model.pth"
  decoder:
    top_paths:    1
    beam_width:   10
    lm_path:      null
    alpha:        0.8
    beta:         1
    cutoff_top_n: 40
    cutoff_prob:  1.0
    lm_workers:   1
  audio_conf:
    sample_rate:          16000
    window_size:          .02
    window_stride:        .01
    window:               'hamming'
    speed_volume_perturb: false
    spec_augment:         false
    noise_dir:            null
    noise_prob:           0.4
    noise_min:            0.0
    noise_max:            0.5

optim:
  max_norm:             400
  learning_anneal:      1.005
  keep_batchnorm_fp32:  null
  loss_scale:           1
  opt_level:            'O1'
  lr:                   1.5e-4
  eps:                  1.0e-8
  betas:                (0.9, 0.999)
  weight_decay:         1.0e-5
  step:                 10
  gamma:                0.1


inference:
  cuda:         true
  half:         false
  manifest:     "checkpoint/jp_1024_5_LSTM/test.json"
  output_file:  "checkpoint/jp_1024_5_LSTM/output.txt"
  batch_size:   10
  num_workers:  32
  restart_from: "zakuro://asrdeepspeech/jp_1024_5_LSTM"

windows:
  'hamming':    "scipy.signal.hamming"
  'hann':       "scipy.signal.hann"
  'blackman':   "scipy.signal.blackman"
  'bartlett':   "scipy.signal.bartlett"

supported_rnns:
  'lstm':       "nn.LSTM"
  'rnn':        "nn.RNN"
  'gru':        "nn.GRU"
